name: Build and Publish image to Docker Hub
on: 
  [workflow_dispach]

jobs: 
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build ./api/ -t
